const fs=require('fs'), vm=require('vm'), assert=require('assert');
function makeElement(id=''){return {id,value:'',textContent:'',innerHTML:'',disabled:false,children:[],dataset:{},style:{},className:'',classList:{add(){},remove(){},toggle(){}},append(...x){this.children.push(...x)},appendChild(x){this.children.push(x);return x},removeChild(){return this.children.pop()},prepend(x){this.children.unshift(x)},remove(){},focus(){},click(){},listeners:{},addEventListener(t,f){this.listeners[t]=f},closest(){return null},tagName:'DIV'};}
function loadApp(storage={}){const elements=new Map();const doc={body:makeElement('body'),getElementById(id){if(!elements.has(id))elements.set(id,makeElement(id));return elements.get(id)},createElement(tag){const e=makeElement();e.tagName=tag.toUpperCase();return e},addEventListener(){}};['sessionPreset','customReps','customDist','debounceSeconds','sessionName','sessionNotes'].forEach(id=>doc.getElementById(id));doc.getElementById('sessionPreset').value='6x400';doc.getElementById('customReps').value='6';doc.getElementById('customDist').value='400';doc.getElementById('debounceSeconds').value='2';doc.getElementById('sessionName').value='Editable';let perf=0;const localStorage={getItem(k){return Object.hasOwn(storage,k)?storage[k]:null},setItem(k,v){storage[k]=String(v)},removeItem(k){delete storage[k]}};const ctx={console,require,document:doc,localStorage,Blob:function(){},URL:{createObjectURL(){return 'blob:'},revokeObjectURL(){}},performance:{now(){return perf}},window:null,alert(m){ctx.alertMsg=m},confirm(){return true},setTimeout(){return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){},Date,addEventListener(){}};ctx.window=ctx;let html=fs.readFileSync('index.html','utf8');let script=html.slice(html.indexOf('<script>')+8,html.lastIndexOf('</script>'));script += `\nthis.__app={setPerf(v){performance.now=()=>v},getElement(id){return document.getElementById(id)},parseRosterCsv,applyRoster,editRoster,startRun,recordRfidKeyboardEvent,recordPassByStudentId,undoLast,buildSessionSnapshot,applyRecoveredSessionSnapshot,buildAcceptedScanProjectionRows,exportCsv,parseRunCsvForAnalytics,get session(){return session},get sessionConfig(){return sessionConfig},get students(){return students}}`;vm.runInNewContext(script,ctx,{filename:'index.html'});return {app:ctx.__app,ctx,storage};}
function test(n,f){try{f();console.log('PASS',n)}catch(e){console.error('FAIL',n);console.error(e);process.exitCode=1}}
function roster(rows){return 'runner_no,tag_id,name,class,start_offset_seconds,active\n'+rows.map(r=>r.join(',')).join('\n')}
function setup(offset=0, n=1){const h=loadApp();let rows=[];for(let i=1;i<=n;i++)rows.push([i,String(i).padStart(4,'0'),'R'+i,'C',i%2?offset:60,true]);h.app.applyRoster(h.app.parseRosterCsv(roster(rows)).students);h.app.startRun();return h}
test('required presets and live custom totals',()=>{const {app}=loadApp();const el=app.getElement('sessionPreset');[['6x400',6,400,2400],['5x480',5,480,2400],['5x400',5,400,2000],['4x400',4,400,1600],['3x400',3,400,1200]].forEach(([v,r,d,t])=>{el.value=v;el.listeners.change();assert.equal(app.getElement('sessionTotal').textContent,String(t));assert.equal(app.sessionConfig.reps,r);assert.equal(app.sessionConfig.repDistanceM,d)});el.value='custom';app.getElement('customReps').value='5';app.getElement('customDist').value='123';el.listeners.change();assert.equal(app.getElement('sessionTotal').textContent,'615')});

test('five-lap presets finish on fifth and reject sixth',()=>{['5x400','5x480'].forEach(preset=>{const h=loadApp();h.app.getElement('sessionPreset').value=preset;h.app.getElement('sessionPreset').listeners.change();h.app.applyRoster(h.app.parseRosterCsv(roster([[1,'0001','A','C',0,true]])).students);h.app.startRun();[50000,100000,150000,200000,250000,300000].forEach(t=>{h.app.setPerf(t);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t',perfMs:t})});assert.equal(h.app.sessionConfig.reps,5);assert.equal(h.app.session.acceptedLaps.length,5);assert.equal(h.app.session.dataById.get('1').splits.length,5);assert.equal(h.app.session.rawHardwareEvents.at(-1).processing_status,'ALREADY_FINISHED');assert.equal(h.app.sessionConfig.totalDistanceM,h.app.sessionConfig.reps*h.app.sessionConfig.repDistanceM)})});
test('session id/name notes debounce default and lock',()=>{const {app}=loadApp();app.getElement('sessionName').value='Named';app.getElement('sessionNotes').value='note';app.getElement('debounceSeconds').value='3.5';app.applyRoster(app.parseRosterCsv(roster([[1,'0001','A','C',0,true]])).students);app.startRun();const id=app.session.sessionId;assert(id);assert.equal(app.sessionConfig.sessionName,'Named');assert.equal(app.sessionConfig.notes,'note');assert.equal(app.session.lockedDebounceMs,3500);app.getElement('debounceSeconds').value='0';assert.equal(app.session.lockedDebounceMs,3500);const snap=app.buildSessionSnapshot('ACTIVE');const h2=loadApp();h2.app.applyRecoveredSessionSnapshot(snap);assert.equal(h2.app.sessionConfig.notes,'note');assert.equal(h2.app.session.lockedDebounceMs,3500);assert.equal(h2.app.session.sessionId,id)});
test('debounce per runner and min lap unchanged',()=>{const h=setup(0,2),a=h.app; a.setPerf(70000);a.recordRfidKeyboardEvent('0001',{wallTimeIso:'t1',perfMs:70000});a.setPerf(71000);a.recordRfidKeyboardEvent('0001',{wallTimeIso:'t2',perfMs:71000});a.setPerf(71500);a.recordRfidKeyboardEvent('0002',{wallTimeIso:'t3',perfMs:71500});a.setPerf(90000);a.recordRfidKeyboardEvent('0001',{wallTimeIso:'t4',perfMs:90000});assert.deepEqual(a.session.rawHardwareEvents.map(e=>e.processing_status),['ACCEPTED','DEBOUNCED','ACCEPTED','TOO_SOON'])});
[0,10,20,60].forEach(off=>test('offset '+off,()=>{const h=setup(off);const t=off===0?70000:off===10?70000:off===20?80000:90000;h.app.setPerf(t);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t',perfMs:t});const lap=h.app.session.acceptedLaps[0];assert.equal(lap.raw_elapsed_ms,t);assert.equal(lap.adjusted_elapsed_ms,t-off*1000);assert.equal(lap.start_offset_seconds,off)}));
test('lap timing with 60s offset and completion',()=>{const h=setup(60);[90000,150000,225000].forEach(t=>{h.app.setPerf(t);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t',perfMs:t})});const rows=h.app.buildAcceptedScanProjectionRows('1').filter(r=>!r.voided);assert.deepEqual(rows.map(r=>r.elapsed_time_seconds),[30,90,165]);assert.deepEqual(rows.map(r=>r.lap_time_seconds),[30,60,75]);h.app.sessionConfig.reps=3;assert.equal(h.app.session.dataById.get('1').splits.length,3)});
test('before wave RFID and tile',()=>{let h=setup(60);h.app.setPerf(30000);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t',perfMs:30000});assert.equal(h.app.session.rawHardwareEvents[0].processing_status,'BEFORE_WAVE_START');assert.equal(h.app.session.acceptedLaps.length,0);h=setup(60);h.app.setPerf(30000);const out=h.app.recordPassByStudentId('1',{source:'TAP'});assert.equal(out.status,'BEFORE_WAVE_START');assert.equal(h.app.session.rawHardwareEvents.length,0);assert.equal(h.app.session.acceptedLaps.length,0)});
test('active offset edits blocked and prior snapshots stable',()=>{const h=setup(10);h.app.setPerf(70000);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t',perfMs:70000});const before=JSON.stringify(h.app.session.acceptedLaps[0]);const res=h.app.editRoster([{runner_no:'1',tag_id:'0001',name:'A','class':'C',start_offset_seconds:'20',active:'true'}]);assert.equal(res.ok,false);assert.equal(JSON.stringify(h.app.session.acceptedLaps[0]),before)});
test('recovery preserves adjusted and next lap uses locked offset once',()=>{const h=setup(60);h.app.setPerf(90000);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t',perfMs:90000});const snap=h.app.buildSessionSnapshot('ACTIVE');const h2=loadApp();h2.app.setPerf(100000);h2.app.applyRecoveredSessionSnapshot(snap);assert.equal(h2.app.session.acceptedLaps[0].adjusted_elapsed_ms,30000);h2.app.setPerf(160000);h2.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t2',perfMs:160000});assert(h2.app.session.acceptedLaps[1].adjusted_elapsed_ms > 90000); assert.equal(h2.app.session.acceptedLaps[1].start_offset_seconds,60)});
test('undo replacement ids and projections',()=>{const h=setup(60);[90000,150000].forEach(t=>{h.app.setPerf(t);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t',perfMs:t})});const old=h.app.session.acceptedLaps[1].lap_id;h.app.undoLast();h.app.setPerf(225000);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t3',perfMs:225000});assert.notEqual(h.app.session.acceptedLaps.at(-1).lap_id,old);assert.deepEqual(h.app.session.dataById.get('1').splits,[30000,165000])});
test('100-runner scale persists with functioning storage',()=>{const h=setup(0,100);assert.equal(h.app.session.persistenceFailed,false);for(let i=1;i<=100;i++){const tag=String(i).padStart(4,'0');const t=i%2?70000:130000;h.app.setPerf(t);h.app.recordRfidKeyboardEvent(tag,{wallTimeIso:'t',perfMs:t})}assert.equal(h.app.session.acceptedLaps.length,100);assert.equal(h.app.session.rawHardwareEvents.length,100);assert.equal(h.app.session.persistenceFailed,false);assert.equal(typeof h.app.exportCsv,'function');assert.equal(typeof h.app.parseRunCsvForAnalytics,'function')});

test('100-runner noisy six-lap scale persists and recovers',()=>{const h=setup(0,100);for(let lap=0;lap<6;lap++){for(let i=1;i<=100;i++){const tag=String(i).padStart(4,'0');const base=(i%2?50000:110000)+(lap*50000);h.app.setPerf(base);h.app.recordRfidKeyboardEvent(tag,{wallTimeIso:'a'+lap+'_'+i,perfMs:base});if(lap===0){h.app.setPerf(base+1000);h.app.recordRfidKeyboardEvent(tag,{wallTimeIso:'d'+i,perfMs:base+1000});h.app.setPerf(base+3000);h.app.recordRfidKeyboardEvent(tag,{wallTimeIso:'s'+i,perfMs:base+3000})}}}for(let i=0;i<100;i++){h.app.setPerf(500000+i);h.app.recordRfidKeyboardEvent(String(9000+i),{wallTimeIso:'u'+i,perfMs:500000+i})}assert.equal(h.app.session.acceptedLaps.length,600);assert.equal(h.app.session.rawHardwareEvents.length,900);assert.equal(h.app.session.persistenceFailed,false);const adjustedBefore=h.app.session.acceptedLaps.map(l=>l.adjusted_elapsed_ms);const scanNumbersBefore=h.app.session.acceptedLaps.map(l=>l.scan_number);const snap=h.app.buildSessionSnapshot('ACTIVE');const h2=loadApp();h2.app.applyRecoveredSessionSnapshot(snap);assert.equal(h2.app.session.rawHardwareEvents.length,900);assert.equal(h2.app.session.acceptedLaps.length,600);assert.deepEqual(h2.app.session.acceptedLaps.map(l=>l.adjusted_elapsed_ms),adjustedBefore);assert.deepEqual(h2.app.session.acceptedLaps.map(l=>l.scan_number),scanNumbersBefore);assert.equal(new Set(h2.app.session.acceptedLaps.map(l=>l.lap_id)).size,600);h2.app.setPerf(700000);h2.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'after',perfMs:700000});assert.equal(h2.app.session.rawHardwareEvents.length,901);assert.equal(h2.app.session.acceptedLaps.length,600);assert.equal(h2.app.session.rawHardwareEvents.at(-1).processing_status,'ALREADY_FINISHED');assert.equal(h2.app.session.persistenceFailed,false)});

test('localStorage setItem failure is isolated and capture continues in memory',()=>{const h=setup(0,1);h.ctx.localStorage.setItem=()=>{throw new Error('quota')};h.app.setPerf(70000);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t',perfMs:70000});assert.equal(h.app.session.persistenceFailed,true);assert.equal(h.app.session.rawHardwareEvents.length,1);assert.equal(h.app.session.acceptedLaps.length,1)});
