const fs=require('fs'), vm=require('vm'), assert=require('assert');
function makeElement(id='',doc){let _html=''; const e={id,value:'',textContent:'',disabled:false,checked:false,children:[],dataset:{},style:{},className:'',tagName:'DIV',listeners:{},classList:{add(c){if(!e.className.split(/\s+/).includes(c))e.className+=(e.className?' ':'')+c},remove(c){e.className=e.className.split(/\s+/).filter(x=>x!==c).join(' ')},toggle(c,v){(v===undefined?!this.contains(c):v)?this.add(c):this.remove(c)},contains(c){return e.className.split(/\s+/).includes(c)}} ,setAttribute(k,v){e[k]=v},append(...x){e.children.push(...x)},appendChild(x){e.children.push(x);return x},removeChild(){return e.children.pop()},prepend(x){e.children.unshift(x)},remove(){},focus(){if(doc)doc.activeElement=e},click(){e.listeners.click&&e.listeners.click({currentTarget:e,target:e,preventDefault(){}})},addEventListener(t,f){e.listeners[t]=f},closest(){return null},querySelector(){return null}};Object.defineProperty(e,'innerHTML',{get(){return _html},set(v){_html=String(v);e.children=[];if(doc){for(const m of _html.matchAll(/<([a-zA-Z]+)[^>]*id="([^"]+)"[^>]*>/g)){const child=doc.getElementById(m[2]);child.tagName=m[1].toUpperCase();e.children.push(child)}}}});return e;}
function load(storage={}){const els=new Map();const doc={activeElement:null,body:null,getElementById(id){if(!els.has(id))els.set(id,makeElement(id,doc));return els.get(id)},createElement(tag){const e=makeElement('',doc);e.tagName=tag.toUpperCase();return e},addEventListener(){}};doc.body=makeElement('body',doc);['sessionPreset','customReps','customDist','debounceSeconds','sessionName','sessionNotes','scanInput','focusWarn','v2ExportStatus'].forEach(id=>doc.getElementById(id));doc.getElementById('sessionPreset').value='6x400';doc.getElementById('customReps').value='6';doc.getElementById('customDist').value='400';doc.getElementById('debounceSeconds').value='2';let perf=0;const ctx={console,require,document:doc,localStorage:{getItem:k=>Object.hasOwn(storage,k)?storage[k]:null,setItem:(k,v)=>{storage[k]=String(v)},removeItem:k=>delete storage[k]},Blob:function(parts){this.text=(parts||[]).join('')},URL:{createObjectURL(){return 'blob:'},revokeObjectURL(){}},performance:{now(){return perf}},window:null,alert(m){ctx.alertMsg=m},confirm(){return true},setTimeout(fn){if(fn)fn();return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){},Date,addEventListener(){}};ctx.window=ctx;let html=fs.readFileSync('index.html','utf8');let script=html.slice(html.indexOf('<script>')+8,html.lastIndexOf('</script>'));script += `\nthis.__app={setPerf(v){performance.now=()=>v},getElement:id=>document.getElementById(id),parseRosterCsv,applyRoster,startRun,endRun,recordRfidKeyboardEvent,buildSessionSnapshot,applyRecoveredSessionSnapshot,buildRawRfidEventsExportRows,buildAcceptedLapsExportRows,buildSessionSummaryExportRows,makeCsv,rosterTagNormalizeForImport,normalizeTagForMatching,get students(){return students},get session(){return session}}`;vm.runInNewContext(script,ctx,{filename:'index.html'});return {app:ctx.__app,ctx,storage};}
function test(n,f){try{f();console.log('PASS',n)}catch(e){console.error('FAIL',n);console.error(e);process.exitCode=1}}
const uidLower='abcdef1234567890abcdef12';
const uidUpper='ABCDEF1234567890ABCDEF12';
const roster=(rows)=>'runner_no,tag_id,name,class,start_offset_seconds,active\n'+rows.map(r=>r.join(',')).join('\n');

test('four-digit and legacy import normalise safely',()=>{const h=load();assert.equal(h.app.rosterTagNormalizeForImport('0001'),'0001');assert.equal(h.app.rosterTagNormalizeForImport('1'),'0001');const r=h.app.parseRosterCsv(roster([[1,'1','A','C',0,true],[2,'0042','B','C',0,true]]));assert.equal(r.ok,true);assert.deepEqual(r.students.map(s=>s.tagId),['0001','0042']);});

test('lowercase and uppercase 24-character UIDs match consistently without changing raw capture',()=>{const h=load();const r=h.app.parseRosterCsv(roster([[7,uidLower,'Runner UID','C',0,true]]));assert.equal(r.ok,true);assert.equal(r.students[0].tagId,uidUpper);h.app.applyRoster(r.students);h.app.startRun();h.app.setPerf(70000);h.app.recordRfidKeyboardEvent(uidLower,{wallTimeIso:'t1',perfMs:70000});let ev=h.app.session.rawHardwareEvents.at(-1);assert.equal(ev.original_tag_value,uidLower);assert.equal(ev.normalized_tag_value,uidUpper);assert.equal(ev.processing_status,'ACCEPTED');assert.equal(h.app.session.acceptedLaps.at(-1).student_id,'7');assert.equal(h.app.session.acceptedLaps.at(-1).tag_id,uidUpper);h.app.setPerf(140000);h.app.recordRfidKeyboardEvent(uidUpper,{wallTimeIso:'t2',perfMs:140000});assert.equal(h.app.session.rawHardwareEvents.at(-1).processing_status,'ACCEPTED');assert.equal(h.app.session.acceptedLaps.at(-1).student_id,'7');});

test('duplicate full UIDs are rejected after case normalisation',()=>{const h=load();const r=h.app.parseRosterCsv(roster([[1,uidLower,'A','C',0,true],[2,uidUpper,'B','C',0,true]]));assert.equal(r.ok,false);assert(r.report.join('\n').includes('duplicate tag_id '+uidUpper));});

test('invalid UID lengths and non-hexadecimal 24-character values are malformed',()=>{const h=load();h.app.applyRoster(h.app.parseRosterCsv(roster([[1,uidUpper,'A','C',0,true]])).students);h.app.startRun();['A'.repeat(23),'A'.repeat(25),'G'.repeat(24)].forEach((tag,i)=>{h.app.setPerf(70000+i*1000);h.app.recordRfidKeyboardEvent(tag,{wallTimeIso:'bad'+i,perfMs:70000+i*1000});assert.equal(h.app.session.rawHardwareEvents.at(-1).processing_status,'MALFORMED');});});

test('unknown valid full UID is retained as UNKNOWN_TAG with raw and normalised values',()=>{const h=load();h.app.applyRoster(h.app.parseRosterCsv(roster([[1,uidUpper,'A','C',0,true]])).students);h.app.startRun();const unknown='111111111111111111111111';h.app.setPerf(70000);h.app.recordRfidKeyboardEvent(unknown,{wallTimeIso:'u',perfMs:70000});const ev=h.app.session.rawHardwareEvents.at(-1);assert.equal(ev.processing_status,'UNKNOWN_TAG');assert.equal(ev.original_tag_value,unknown);assert.equal(ev.normalized_tag_value,unknown);});

test('debounce works for full UIDs',()=>{const h=load();h.app.applyRoster(h.app.parseRosterCsv(roster([[1,uidUpper,'A','C',0,true]])).students);h.app.startRun();h.app.setPerf(70000);h.app.recordRfidKeyboardEvent(uidUpper,{wallTimeIso:'a',perfMs:70000});h.app.setPerf(71000);h.app.recordRfidKeyboardEvent(uidLower,{wallTimeIso:'b',perfMs:71000});assert.equal(h.app.session.rawHardwareEvents.at(-1).processing_status,'DEBOUNCED');assert.equal(h.app.session.acceptedLaps.length,1);});

test('recovery preserves full UID values and matching',()=>{const storage={};let h=load(storage);h.app.applyRoster(h.app.parseRosterCsv(roster([[1,uidUpper,'A','C',0,true]])).students);h.app.startRun();h.app.setPerf(70000);h.app.recordRfidKeyboardEvent(uidLower,{wallTimeIso:'a',perfMs:70000});const snap=h.app.buildSessionSnapshot('ACTIVE');h=load();h.app.applyRecoveredSessionSnapshot(snap);assert.equal(h.app.session.rawHardwareEvents[0].original_tag_value,uidLower);assert.equal(h.app.session.rawHardwareEvents[0].normalized_tag_value,uidUpper);h.app.setPerf(140000);h.app.recordRfidKeyboardEvent(uidLower,{wallTimeIso:'b',perfMs:140000});assert.equal(h.app.session.rawHardwareEvents.at(-1).processing_status,'ACCEPTED');assert.equal(h.app.session.acceptedLaps.at(-1).student_id,'1');});

test('raw accepted-lap and summary exports retain tag IDs as text and full UID is not truncated',()=>{const h=load();h.app.applyRoster(h.app.parseRosterCsv(roster([[1,uidUpper,'A','C',0,true]])).students);h.app.startRun();h.app.setPerf(70000);h.app.recordRfidKeyboardEvent(uidLower,{wallTimeIso:'a',perfMs:70000});const raw=h.app.makeCsv(h.app.buildRawRfidEventsExportRows());const laps=h.app.makeCsv(h.app.buildAcceptedLapsExportRows());const summary=h.app.makeCsv(h.app.buildSessionSummaryExportRows('2026-07-20T00:00:00.000Z'));assert(raw.includes(uidLower));assert(raw.includes(uidUpper));assert(laps.includes(uidUpper));assert(summary.includes('raw_event_count'));assert(!raw.includes(uidUpper.slice(0,4)+','));});

test('90-runner temporary full-UID roster imports successfully',()=>{const h=load();let rows=[];for(let i=1;i<=90;i++){const hex=String(i).padStart(24,'0');rows.push([i,hex,'R'+i,'C',0,true]);}const r=h.app.parseRosterCsv(roster(rows));assert.equal(r.ok,true);assert.equal(r.students.length,90);assert.equal(r.students[89].tagId,'000000000000000000000090');});
