const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
function makeElement(id='') { return { id, value:'', textContent:'', innerHTML:'', disabled:false, children:[], dataset:{}, style:{}, className:'', classList:{add(){},remove(){},toggle(){}}, append(...x){this.children.push(...x)}, appendChild(x){this.children.push(x);return x}, removeChild(){return this.children.pop()}, prepend(x){this.children.unshift(x)}, remove(){}, focus(){}, click(){}, listeners:{}, addEventListener(type,fn){this.listeners[type]=fn}, closest(){return null}, tagName:'DIV' }; }
function loadApp(storage={}) { const elements=new Map(); const document={ body:makeElement('body'), getElementById(id){ if(!elements.has(id)) elements.set(id,makeElement(id)); return elements.get(id); }, createElement(tag){ const e=makeElement(); e.tagName=tag.toUpperCase(); return e; }, addEventListener(){} }; const localStorage={ getItem(k){return Object.prototype.hasOwnProperty.call(storage,k)?storage[k]:null}, setItem(k,v){storage[k]=String(v)}, removeItem(k){delete storage[k]} }; let perf=0; const context={ console, require, document, localStorage, Blob:function(){}, URL:{createObjectURL(){return 'blob:'},revokeObjectURL(){}}, performance:{now(){return perf}}, window:null, alert(){}, confirm(){return true}, setTimeout(){return 1}, clearTimeout(){}, setInterval(){return 1}, clearInterval(){}, Date, addEventListener(){} }; context.window=context; let html=fs.readFileSync('index.html','utf8'); let script=html.slice(html.indexOf('<script>')+8, html.lastIndexOf('</script>')); script += `\nthis.__app={ setPerf(v){ performance.now=()=>v; }, parseRosterCsv, applyRoster, editRoster, sampleV2RosterCsv, rosterTagNormalizeForImport, loadSavedRosterFromStorage, saveRosterToStorage, renderRosterEditor, getElement(id){return document.getElementById(id)}, setStudents(v){ setStudents(v); initSessionData(); }, get students(){return students}, get session(){return session}, startRun, endRun, recordRfidKeyboardEvent, recordPassByStudentId, buildSessionSnapshot, applyRecoveredSessionSnapshot, getActiveStudents, getDataIds(){return Array.from(session.dataById.keys())}, lookupTag(t){return tagToRunnerId.get(t)} };` ; vm.runInNewContext(script, context, {filename:'index.html'}); return {app:context.__app, context, storage}; }
function test(name, fn){ try{ fn(); console.log('PASS', name); } catch(e){ console.error('FAIL', name); console.error(e); process.exitCode=1; } }
const v2 = 'runner_no,tag_id,name,class,start_offset_seconds,active\n1,0001,A,4F,0,true\n2,0010,B,4F,10,yes\n3,0020,, ,20,1\n4,0004,Inactive,4F,0,false';

test('valid V2 roster and sample headers',()=>{ const {app}=loadApp(); const r=app.parseRosterCsv(v2); assert.equal(r.ok,true); assert.equal(r.students.length,4); assert.equal(r.students[3].active,false); assert(app.sampleV2RosterCsv().startsWith('runner_no,tag_id,name,class,start_offset_seconds,active')); });

test('roster sizes 1 43 80 100 and 120 import',()=>{ const {app}=loadApp(); for (const n of [1,43,80,100,120]) { let csv='runner_no,tag_id,name,class,start_offset_seconds,active\n'; for(let i=1;i<=n;i++) csv += `${i},${String(i).padStart(4,'0')},,,0,true\n`; const r=app.parseRosterCsv(csv); assert.equal(r.ok,true, String(n)); assert.equal(r.students.length,n); } });

test('normalisation and duplicate validations',()=>{ const {app}=loadApp(); assert.equal(app.rosterTagNormalizeForImport('1'),'0001'); assert.equal(app.rosterTagNormalizeForImport('01'),'0001'); assert.equal(app.rosterTagNormalizeForImport('001'),'0001'); assert.equal(app.rosterTagNormalizeForImport('0001'),'0001'); assert.equal(app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n1,1,,,0,true\n2,0001,,,0,true').ok,false); assert.equal(app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n1,0001,,,0,true\n1,0002,,,0,true').ok,false); });

test('required runner offset and active validation',()=>{ const {app}=loadApp(); assert.equal(app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n,0001,,,0,true').ok,false); assert.equal(app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n1,0001,,,-1,true').ok,false); assert.equal(app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n1,0001,,,x,true').ok,false); assert.equal(app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n1,0001,,,0,maybe').ok,false); assert.equal(app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n1,0001,,,0,FALSE').ok,true); });

test('invalid replacement leaves current roster unchanged and legacy migrates',()=>{ const {app}=loadApp(); app.applyRoster(app.parseRosterCsv(v2).students); const before=JSON.stringify(app.students); const bad=app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n1,0001,,,0,true\n2,1,,,0,true'); assert.equal(bad.ok,false); assert.equal(JSON.stringify(app.students),before); const legacy=app.parseRosterCsv('tagId,name,class,gender,age_group,email\n0007,Legacy,4F,F,16,a@example.test'); assert.equal(legacy.ok,true); assert.equal(legacy.students[0].runner_no,'1'); assert.equal(legacy.students[0].start_offset_seconds,0); assert.equal(legacy.students[0].active,true); assert.equal(legacy.message.includes('Legacy'),true); });

test('leading zeros survive save restore and older snapshot migration',()=>{ const storage={}; let h=loadApp(storage); h.app.applyRoster(h.app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n7,0007,Lead,4F,3,true').students); assert(storage.runTimingRosterV2.includes('0007')); assert.equal(storage.runTimingRosterV1, undefined); const snap={schema:'runTimingSessionV2Stage1',schemaVersion:3,savedAtWallTimeIso:'save',status:'ACTIVE',session:{sessionId:'s',started:true,elapsedMsAtSave:70000},sessionConfig:{label:'x',reps:3,repDistanceM:800},students:[{id:'0007',name:'Old',tagId:'0007'}],dataById:{'0007':{splits:[70000]}},rawHardwareEvents:[]}; h=loadApp(); h.app.applyRecoveredSessionSnapshot(snap); assert.equal(h.app.students[0].id,'0007'); assert.equal(h.app.session.acceptedLaps[0].tag_id,'0007'); });

test('stable identity after tag edit and future scan uses edited tag without rewriting history',()=>{ const {app}=loadApp(); app.applyRoster(app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n7,0007,Original,4F,5,true').students); app.startRun(); app.setPerf(70000); app.recordRfidKeyboardEvent('0007',{wallTimeIso:'t1',perfMs:70000}); const rawBefore=JSON.stringify(app.session.rawHardwareEvents[0]); const lapBefore={...app.session.acceptedLaps[0]}; const edit=app.editRoster([{runner_no:'7',tag_id:'9999',name:'Edited',class:'5G',start_offset_seconds:'9',active:'true'}]); assert.equal(edit.ok,true); app.setPerf(140000); app.recordRfidKeyboardEvent('9999',{wallTimeIso:'t2',perfMs:140000}); assert.equal(app.session.acceptedLaps.length,2); assert.equal(app.session.acceptedLaps[1].student_id,'7'); assert.equal(app.session.acceptedLaps[1].tag_id,'9999'); assert.deepEqual(app.session.acceptedLaps[0],lapBefore); assert.equal(JSON.stringify(app.session.rawHardwareEvents[0]),rawBefore); });

test('inactive runner raw event and excluded counts',()=>{ const {app}=loadApp(); app.applyRoster(app.parseRosterCsv(v2).students); assert.equal(app.getActiveStudents().length,3); app.startRun(); app.setPerf(70000); app.recordRfidKeyboardEvent('0004',{wallTimeIso:'t',perfMs:70000}); assert.equal(app.session.rawHardwareEvents.at(-1).processing_status,'INACTIVE_RUNNER'); assert.equal(app.session.acceptedLaps.length,0); });

test('offset is snapped but adjusted remains raw and storage failure visible',()=>{ const h=loadApp(); h.app.applyRoster(h.app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n1,0001,A,C,20,true').students); h.app.startRun(); h.app.setPerf(70000); h.context.localStorage.setItem=()=>{throw new Error('quota')}; h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t',perfMs:70000}); const lap=h.app.session.acceptedLaps[0]; assert.equal(lap.start_offset_seconds,20); assert.equal(lap.adjusted_elapsed_ms,lap.raw_elapsed_ms); assert.equal(h.app.session.persistenceFailed,true); });


test('V2 storage migrates V1 without rewriting sentinel and forget removes only V2',()=>{ const sentinel=JSON.stringify([{id:'0007',tagId:'0007',name:'Legacy Zero',class:'4F'}]); const storage={runTimingRosterV1:sentinel}; const {app}=loadApp(storage); const loaded=app.loadSavedRosterFromStorage(); assert.equal(loaded.ok,true); assert.equal(loaded.students[0].id,'1'); assert.equal(loaded.students[0].runner_no,'1'); assert.equal(loaded.students[0].tagId,'0007'); assert(storage.runTimingRosterV2.includes('runTimingRosterV2')); assert.equal(storage.runTimingRosterV1,sentinel); const btn=app.getElement('btnForgetRoster'); btn.listeners.click(); assert.equal(storage.runTimingRosterV2,undefined); assert.equal(storage.runTimingRosterV1,sentinel); });

test('invalid V1 fallback remains untouched and V2 is preferred',()=>{ const invalid='not-json'; const v2=JSON.stringify({schema:'runTimingRosterV2',schemaVersion:1,students:[{runner_no:'9',tagId:'0009',name:'V2',runner_class:'C',start_offset_seconds:0,active:true}]}); let h=loadApp({runTimingRosterV1:invalid}); assert.equal(h.app.loadSavedRosterFromStorage(),null); assert.equal(h.storage.runTimingRosterV1,invalid); h=loadApp({runTimingRosterV1:JSON.stringify([{id:'0001',tagId:'0001',name:'V1'}]), runTimingRosterV2:v2}); const loaded=h.app.loadSavedRosterFromStorage(); assert.equal(loaded.source,'v2'); assert.equal(loaded.students[0].runner_no,'9'); });

test('inactive matched tag and unknown tag are distinguished',()=>{ const {app}=loadApp(); app.applyRoster(app.parseRosterCsv(v2).students); app.startRun(); app.setPerf(70000); app.recordRfidKeyboardEvent('0004',{wallTimeIso:'t1',perfMs:70000}); app.recordRfidKeyboardEvent('0999',{wallTimeIso:'t2',perfMs:71000}); assert.equal(app.session.rawHardwareEvents[0].processing_status,'INACTIVE_RUNNER'); assert.equal(app.session.rawHardwareEvents[1].processing_status,'UNKNOWN_TAG'); });

test('visible roster editor applies valid change and rejects invalid one',()=>{ const {app}=loadApp(); app.applyRoster(app.parseRosterCsv('runner_no,tag_id,name,class,start_offset_seconds,active\n1,0001,A,C,0,true').students); const toggle=app.getElement('btnToggleRosterEditor'); toggle.listeners.click(); const text=app.getElement('rosterEditorText'); const apply=app.getElement('btnApplyRosterEdits'); assert(text.value.includes('runner_no,tag_id,name,class,start_offset_seconds,active')); text.value='runner_no,tag_id,name,class,start_offset_seconds,active\n1,0002,A2,C2,0,true'; apply.listeners.click(); assert.equal(app.students[0].tagId,'0002'); text.value='runner_no,tag_id,name,class,start_offset_seconds,active\n1,0002,A2,C2,-5,true'; apply.listeners.click(); assert.equal(app.students[0].tagId,'0002'); assert(app.getElement('rosterEditorStatus').textContent.includes('start_offset_seconds')); });


test('legacy saved roster migration uses runner_no as canonical identity across tag edits',()=>{ const sentinel=JSON.stringify([{tagId:'0007',name:'Test Runner'}]); const {app,storage}=loadApp({runTimingRosterV1:sentinel}); assert.equal(storage.runTimingRosterV1,sentinel); assert(storage.runTimingRosterV2.includes('Test Runner')); const runner=app.students[0]; assert.equal(runner.runner_no,'1'); assert.equal(runner.id,'1'); assert.equal(runner.tagId,'0007'); assert.equal(app.lookupTag('0007'),'1'); assert.deepEqual(app.getDataIds(),['1']); app.startRun(); app.setPerf(70000); app.recordRfidKeyboardEvent('0007',{wallTimeIso:'t1',perfMs:70000}); const rawBefore=JSON.stringify(app.session.rawHardwareEvents[0]); const lapBefore={...app.session.acceptedLaps[0]}; assert.equal(lapBefore.student_id,'1'); assert.equal(lapBefore.runner_no,'1'); assert.equal(lapBefore.tag_id,'0007'); const edited=app.editRoster([{runner_no:'1',tag_id:'9999',name:'Test Runner',class:'',start_offset_seconds:'0',active:'true'}]); assert.equal(edited.ok,true); assert.equal(app.students[0].runner_no,'1'); assert.equal(app.students[0].id,'1'); assert.equal(app.lookupTag('9999'),'1'); assert.equal(app.lookupTag('0007'),undefined); assert.equal(JSON.stringify(app.session.rawHardwareEvents[0]),rawBefore); assert.deepEqual(app.session.acceptedLaps[0],lapBefore); app.setPerf(140000); app.recordRfidKeyboardEvent('9999',{wallTimeIso:'t2',perfMs:140000}); assert.equal(app.session.acceptedLaps.at(-1).student_id,'1'); assert.equal(app.session.acceptedLaps.at(-1).tag_id,'9999'); app.setPerf(210000); app.recordRfidKeyboardEvent('0007',{wallTimeIso:'t3',perfMs:210000}); assert.equal(app.session.rawHardwareEvents.at(-1).processing_status,'UNKNOWN_TAG'); assert.deepEqual(app.getDataIds(),['1']); });

test('two-row legacy saved roster gets deterministic unique identities without runner/tag collision',()=>{ const {app}=loadApp({runTimingRosterV1:JSON.stringify([{tagId:'0001',name:'One'},{tagId:'0002',name:'Two'}])}); assert.deepEqual(app.students.map(s=>s.runner_no),['1','2']); assert.deepEqual(app.students.map(s=>s.id),['1','2']); assert.equal(app.lookupTag('0001'),'1'); assert.equal(app.lookupTag('0002'),'2'); app.startRun(); app.setPerf(70000); app.recordRfidKeyboardEvent('0002',{wallTimeIso:'t',perfMs:70000}); assert.equal(app.session.acceptedLaps[0].student_id,'2'); assert.equal(app.session.acceptedLaps[0].runner_no,'2'); assert.equal(app.session.acceptedLaps[0].tag_id,'0002'); assert.deepEqual(app.getDataIds(),['1','2']); });
