const fs=require('fs'), vm=require('vm'), assert=require('assert');
function makeElement(id=''){return {id,value:'',textContent:'',innerHTML:'',disabled:false,children:[],dataset:{},style:{},className:'',classList:{add(){},remove(){},toggle(){}},append(...x){this.children.push(...x)},appendChild(x){this.children.push(x);return x},removeChild(){return this.children.pop()},prepend(x){this.children.unshift(x)},remove(){},focus(){},click(){},listeners:{},addEventListener(t,f){this.listeners[t]=f},closest(){return null},tagName:'DIV'};}
function loadApp(storage={}){const elements=new Map();const doc={body:makeElement('body'),getElementById(id){if(!elements.has(id))elements.set(id,makeElement(id));return elements.get(id)},createElement(tag){const e=makeElement();e.tagName=tag.toUpperCase();return e},addEventListener(){}};['sessionPreset','customReps','customDist','debounceSeconds','sessionName','sessionNotes'].forEach(id=>doc.getElementById(id));doc.getElementById('sessionPreset').value='6x400';doc.getElementById('customReps').value='6';doc.getElementById('customDist').value='400';doc.getElementById('debounceSeconds').value='2';let perf=0;const localStorage={getItem(k){return Object.hasOwn(storage,k)?storage[k]:null},setItem(k,v){storage[k]=String(v)},removeItem(k){delete storage[k]}};const ctx={console,require,document:doc,localStorage,Blob:function(){},URL:{createObjectURL(){return 'blob:'},revokeObjectURL(){}},performance:{now(){return perf}},window:null,alert(m){ctx.alertMsg=m},confirm(){return true},setTimeout(){return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){},Date,addEventListener(){}};ctx.window=ctx;let html=fs.readFileSync('index.html','utf8');let script=html.slice(html.indexOf('<script>')+8,html.lastIndexOf('</script>'));script += `\nthis.__app={setPerf(v){performance.now=()=>v},getElement(id){return document.getElementById(id)},parseRosterCsv,applyRoster,startRun,endRun,recordRfidKeyboardEvent,recordPassByStudentId,manualAddCurrentLap,manualAddCorrectedLap,manualAddCorrectedLapFromInput,parseCorrectedElapsedInput,formatCorrectedElapsedInput,voidAcceptedLap,undoLast,buildSessionSnapshot,applyRecoveredSessionSnapshot,buildAcceptedScanProjectionRows,get session(){return session},get sessionConfig(){return sessionConfig},get students(){return students}}`;vm.runInNewContext(script,ctx,{filename:'index.html'});return {app:ctx.__app,ctx,storage};}
function test(n,f){try{f();console.log('PASS',n)}catch(e){console.error('FAIL',n);console.error(e);process.exitCode=1}}
function roster(rows){return 'runner_no,tag_id,name,class,start_offset_seconds,active\n'+rows.map(r=>r.join(',')).join('\n')}
function setup(offset=0,n=1,storage={}){const h=loadApp(storage);let rows=[];for(let i=1;i<=n;i++)rows.push([i,String(i).padStart(4,'0'),'R'+i,'C',i===1?offset:0,true]);h.app.applyRoster(h.app.parseRosterCsv(roster(rows)).students);h.app.startRun();return h}

test('current manual creates correction lap manual and no raw',()=>{const h=setup();h.app.setPerf(70000);const r=h.app.manualAddCurrentLap('1',{operationId:'a'});assert(r.ok);assert.equal(h.app.session.correctionEvents[0].action,'MANUAL_ADD_CURRENT');assert.equal(h.app.session.acceptedLaps[0].source,'MANUAL');assert.equal(h.app.session.rawHardwareEvents.length,0)});
test('current manual offset and before wave rejected',()=>{let h=setup(60);h.app.setPerf(90000);h.app.manualAddCurrentLap('1');assert.equal(h.app.session.acceptedLaps[0].adjusted_elapsed_ms,30000);h=setup(60);h.app.setPerf(30000);assert.equal(h.app.manualAddCurrentLap('1').status,'BEFORE_WAVE_START')});
test('corrected parsing formats and invalid',()=>{const a=setup().app;[['90',90000],['02:30',150000],['02:30.1',150100],['02:30.12',150120],['02:30.123',150123]].forEach(([t,ms])=>assert.deepEqual(a.parseCorrectedElapsedInput(t),{ok:true,valueMs:ms}));assert(!a.parseCorrectedElapsedInput('x').ok);assert.equal(a.formatCorrectedElapsedInput(150123),'02:30.123')});
test('corrected before offset and reason required',()=>{const h=setup(60);h.app.setPerf(120000);assert.equal(h.app.manualAddCorrectedLap('1',30000,{reason:'late'}).status,'BEFORE_WAVE_START');assert.equal(h.app.manualAddCorrectedLap('1',90000).status,'REASON_REQUIRED')});
test('corrected insertion keeps IDs recalculates projection',()=>{const h=setup();h.app.setPerf(250000);h.app.manualAddCorrectedLap('1',70000,{reason:'a'});h.app.manualAddCorrectedLap('1',190000,{reason:'b'});const ids=h.app.session.acceptedLaps.map(l=>l.lap_id);h.app.manualAddCorrectedLap('1',130000,{reason:'miss'});assert.deepEqual(h.app.session.acceptedLaps.slice(0,2).map(l=>l.lap_id),ids);assert.deepEqual(h.app.buildAcceptedScanProjectionRows('1').filter(r=>!r.voided).sort((a,b)=>a.lap_number-b.lap_number).map(r=>r.lap_time_seconds),[70,60,60])});
test('max lap blocked void replacement completes with new ids',()=>{const h=setup();h.app.setPerf(250000);h.app.sessionConfig.reps=2;h.app.manualAddCorrectedLap('1',70000,{reason:'a'});h.app.manualAddCorrectedLap('1',140000,{reason:'b'});assert.equal(h.app.manualAddCorrectedLap('1',210000,{reason:'c'}).status,'ALREADY_FINISHED');const old=h.app.session.acceptedLaps[1].lap_id;h.app.voidAcceptedLap(old,{reason:'bad'});assert.equal(h.app.session.dataById.get('1').splits.length,1);h.app.manualAddCorrectedLap('1',210000,{reason:'replace'});assert.equal(h.app.session.dataById.get('1').splits.length,2);assert.notEqual(h.app.session.acceptedLaps.at(-1).lap_id,old)});
test('void reason duplicate and source unchanged',()=>{const h=setup();h.app.setPerf(100000);h.app.manualAddCorrectedLap('1',70000,{reason:'a'});const lap=h.app.session.acceptedLaps[0];assert.equal(h.app.voidAcceptedLap(lap.lap_id,{}).status,'REASON_REQUIRED');h.app.voidAcceptedLap(lap.lap_id,{reason:'bad'});const n=h.app.session.correctionEvents.length;h.app.voidAcceptedLap(lap.lap_id,{reason:'again'});assert.equal(h.app.session.correctionEvents.length,n);assert.equal(lap.source_event_id,h.app.session.correctionEvents[0].correction_event_id)});
test('quick undo voids last global with automatic reason',()=>{const h=setup(0,2);h.app.setPerf(100000);h.app.manualAddCorrectedLap('1',70000,{reason:'a'});h.app.manualAddCorrectedLap('2',80000,{reason:'b'});h.app.undoLast();assert.equal(h.app.session.acceptedLaps[1].voided,true);assert.equal(h.app.session.acceptedLaps[1].correction_reason,'Quick Undo');assert.equal(h.app.session.correctionEvents.at(-1).action,'QUICK_UNDO')});
test('idempotency guard prevents duplicate addition',()=>{const h=setup();h.app.setPerf(70000);h.app.manualAddCurrentLap('1',{operationId:'same'});const r=h.app.manualAddCurrentLap('1',{operationId:'same'});assert(r.duplicate);assert.equal(h.app.session.acceptedLaps.length,1)});
test('related raw links retained debounced without mutation and tile tap no raw',()=>{const h=setup();h.app.setPerf(70000);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t',perfMs:70000});h.app.setPerf(71000);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t2',perfMs:71000});const raw=h.app.session.rawHardwareEvents[1], before=JSON.stringify(raw);h.app.setPerf(200000);h.app.manualAddCorrectedLap('1',130000,{reason:'debounced recovery',relatedRawEventId:raw.event_id});assert.equal(h.app.session.correctionEvents.at(-1).related_raw_event_id,raw.event_id);assert.equal(JSON.stringify(raw),before);const h2=setup();h2.app.setPerf(70000);h2.app.recordPassByStudentId('1',{source:'TAP'});assert.equal(h2.app.session.correctionEvents.length,1);assert.equal(h2.app.session.rawHardwareEvents.length,0)});
test('recovery preserves corrections ids links projections and next unique',()=>{const h=setup();h.app.setPerf(200000);h.app.manualAddCorrectedLap('1',70000,{reason:'a'});h.app.voidAcceptedLap(h.app.session.acceptedLaps[0].lap_id,{reason:'bad'});const snap=h.app.buildSessionSnapshot('ACTIVE');const h2=loadApp();h2.app.applyRecoveredSessionSnapshot(snap);assert.deepEqual(h2.app.session.correctionEvents.map(e=>e.correction_event_id),h.app.session.correctionEvents.map(e=>e.correction_event_id));h2.app.manualAddCorrectedLap('1',140000,{reason:'new'});assert.equal(new Set(h2.app.session.correctionEvents.map(e=>e.correction_event_id)).size,3);assert.equal(h2.app.buildAcceptedScanProjectionRows('1')[0].lap_number,null)});
test('persistence failure keeps data warning and clean projection voids',()=>{const h=setup();h.app.setPerf(100000);h.ctx.localStorage.setItem=()=>{throw new Error('quota')};h.app.manualAddCorrectedLap('1',70000,{reason:'a'});h.app.voidAcceptedLap(h.app.session.acceptedLaps[0].lap_id,{reason:'bad'});assert.equal(h.app.session.persistenceFailed,true);const row=h.app.buildAcceptedScanProjectionRows('1')[0];assert.equal(row.voided,true);assert.equal(row.lap_number,null);assert.equal(row.status,'VOIDED');assert.equal(row.source,'MANUAL');assert.equal(row.correction_reason,'bad')});
test('100 runner session with corrections functional',()=>{const h=setup(0,100);h.app.setPerf(200000);for(let i=1;i<=100;i++)h.app.manualAddCorrectedLap(String(i),70000+i,{reason:'seed'});assert.equal(h.app.session.acceptedLaps.length,100);assert.equal(h.app.session.correctionEvents.length,100)});


test('current-time manual after end is rejected without data',()=>{const h=setup();h.app.setPerf(100000);h.app.endRun();const before=[h.app.session.correctionEvents.length,h.app.session.acceptedLaps.length];const r=h.app.manualAddCurrentLap('1');assert.equal(r.status,'SESSION_NOT_ACTIVE');assert.deepEqual([h.app.session.correctionEvents.length,h.app.session.acceptedLaps.length],before)});
test('corrected insertion active and after end respects future bounds and persists completed snapshot',()=>{const storage={};const h=setup(0,1,storage);h.app.setPerf(100000);let r=h.app.manualAddCorrectedLap('1',90000,{reason:'active'});assert(r.ok);assert.equal(h.app.manualAddCorrectedLap('1',110000,{reason:'future'}).status,'FUTURE_TIME');h.app.setPerf(200000);h.app.endRun();const n=h.app.session.acceptedLaps.length;r=h.app.manualAddCorrectedLap('1',150000,{reason:'post'});assert(r.ok);assert.equal(h.app.manualAddCorrectedLap('1',250000,{reason:'future ended'}).status,'FUTURE_TIME');assert.equal(h.app.session.acceptedLaps.length,n+1);const snap=JSON.parse(storage.runTimingSessionV2Stage1);assert.equal(snap.status,'COMPLETED');assert.equal(snap.acceptedLaps.length,n+1);const h2=loadApp(storage);h2.app.applyRecoveredSessionSnapshot(snap);assert.equal(h2.app.session.acceptedLaps.length,n+1);assert.equal(h2.app.session.correctionEvents.length,2)});
test('post-session void and quick undo persist through refresh',()=>{const storage={};const h=setup(0,2,storage);h.app.setPerf(100000);h.app.manualAddCurrentLap('1');h.app.setPerf(110000);h.app.manualAddCurrentLap('2');h.app.setPerf(150000);h.app.endRun();h.app.voidAcceptedLap(h.app.session.acceptedLaps[0].lap_id,{reason:'post void'});h.app.undoLast();assert.equal(h.app.session.acceptedLaps[0].voided,true);assert.equal(h.app.session.acceptedLaps[1].correction_reason,'Quick Undo');const snap=JSON.parse(storage.runTimingSessionV2Stage1);const h2=loadApp(storage);h2.app.applyRecoveredSessionSnapshot(snap);assert.equal(h2.app.session.acceptedLaps.filter(l=>l.voided).length,2);assert.equal(h2.app.session.correctionEvents.at(-1).action,'QUICK_UNDO')});
test('older snapshot without correctionEvents restores empty correction audit',()=>{const h=setup();h.app.setPerf(90000);h.app.recordRfidKeyboardEvent('0001',{wallTimeIso:'t',perfMs:90000});const snap=h.app.buildSessionSnapshot('ACTIVE');delete snap.correctionEvents;delete snap.correctionEventCounter;delete snap.correctionOperationIds;const h2=loadApp();h2.app.applyRecoveredSessionSnapshot(snap);assert.deepEqual(h2.app.session.correctionEvents,[]);h2.app.setPerf(120000);const r=h2.app.manualAddCurrentLap('1');assert(r.ok);assert.equal(h2.app.session.correctionEvents.length,1);assert.match(h2.app.session.correctionEvents[0].correction_event_id,/corr_/)});
